HEADERS += ./GUI/global.h \
    ./GUI/SubScene.h \
    ./GUI/Workspace.h \
    ./GUI/Scene.h \
    ./GUI/QMeshDoc.h \
    ./GUI/Tools/MeshInfoPanel.h \
    ./GUI/Tools/TransformationPanel.h \
    ./GraphicsLibrary/Mesh/QSegMesh.h \
    ./GraphicsLibrary/Mesh/QSurfaceMesh.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/properties.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Quadric.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Surface_mesh.h \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Vector.h \
    ./GraphicsLibrary/Basic/Line.h \
    ./GraphicsLibrary/Basic/Plane.h \
    ./GraphicsLibrary/Basic/PolygonArea.h \
    ./GraphicsLibrary/Basic/Triangle.h \
    ./GraphicsLibrary/SpacePartition/Octree.h \
    ./GraphicsLibrary/Sampling/EdgeSampler.h \
    ./GraphicsLibrary/Sampling/RegularRecursive.h \
    ./GraphicsLibrary/Sampling/Sampler.h \
    ./GraphicsLibrary/Sampling/SliceSampling.h \
    ./GraphicsLibrary/Sampling/SpherePackSampling.h \
    ./GraphicsLibrary/Sampling/VoxelSampling.h \
    ./GraphicsLibrary/Voxel/Voxel.h \
    ./GraphicsLibrary/Voxel/Voxeler.h \
    ./GraphicsLibrary/Skeleton/ClosedPolygon.h \
    ./GraphicsLibrary/Skeleton/GeneralizedCylinder.h \
    ./GraphicsLibrary/Skeleton/PriorityQueue.h \
    ./GraphicsLibrary/Skeleton/RMF.h \
    ./GraphicsLibrary/Skeleton/Skeleton.h \
    ./GraphicsLibrary/Skeleton/SkeletonEdge.h \
    ./GraphicsLibrary/Skeleton/SkeletonExtract.h \
    ./GraphicsLibrary/Skeleton/SkeletonNode.h \
    ./GraphicsLibrary/Skeleton/VertexRecord.h \
    ./Utility/ColorMap.h \
    ./Utility/Graph.h \
    ./Utility/HashTable.h \
    ./Utility/Macros.h \
    ./Utility/NoiseGen.h \
    ./Utility/SimpleDraw.h \
    ./Utility/Sleeper.h \
    ./Utility/Stats.h \
    ./GL/VBO/VBO.h \
    ./GL/GLee.h \
    ./MathLibrary/Bounding/BoundingBox.h \
    ./MathLibrary/Bounding/ConvexHull2.h \
    ./MathLibrary/Bounding/ConvexHull3.h \
    ./MathLibrary/Bounding/MinOBB2.h \
    ./MathLibrary/Bounding/MinOBB3.h \
    ./MathLibrary/Bounding/OBB.h \
    ./MathLibrary/Bounding/OBB2.h \
    ./MathLibrary/Bounding/OBB2_math.h \
    ./MathLibrary/Deformer/DeformerPanel.h \
    ./MathLibrary/Deformer/QVoxelDeformerPanel.h \
    ./MathLibrary/Deformer/VoxelDeformer.h \
    ./MathLibrary/Deformer/FFD.h \
    ./MathLibrary/Deformer/QFFD.h \
    ./MathLibrary/Deformer/QControlPoint.h \
    ./MathLibrary/Coordiantes/GCDeformation.h \
    ./Stacker/EditSuggestion.h \
    ./Stacker/Offset.h \
    ./Stacker/ShapeState.h \
    ./Stacker/HiddenViewer.h \
    ./Stacker/StackerPanel.h \
    ./Stacker/StackerPreview.h \
    ./Stacker/ControllerPanel.h \
    ./Stacker/GroupPanel.h \
    ./Stacker/QDeformController.h \
    ./Stacker/ConcentricGroup.h \
    ./Stacker/CoplanarGroup.h \
    ./Stacker/Group.h \
    ./Stacker/JointGroup.h \
    ./Stacker/SymmetryGroup.h \
    ./Stacker/Controller.h \
    ./Stacker/Cuboid.h \
    ./Stacker/Primitive.h \
    ./Stacker/GCylinder.h
SOURCES += ./GUI/global.cpp \
    ./GUI/main.cpp \
    ./GUI/QMeshDoc.cpp \
    ./GUI/Scene.cpp \
    ./GUI/SubScene.cpp \
    ./GUI/Workspace.cpp \
    ./GUI/Tools/MeshInfoPanel.cpp \
    ./GUI/Tools/TransformationPanel.cpp \
    ./GraphicsLibrary/Mesh/QSegMesh.cpp \
    ./GraphicsLibrary/Mesh/QSurfaceMesh.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_obj.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_off.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/IO_stl.cpp \
    ./GraphicsLibrary/Mesh/SurfaceMesh/Surface_mesh.cpp \
    ./GraphicsLibrary/Basic/Line.cpp \
    ./GraphicsLibrary/Basic/Plane.cpp \
    ./GraphicsLibrary/Basic/Triangle.cpp \
    ./GraphicsLibrary/SpacePartition/kdtree.cpp \
    ./GraphicsLibrary/SpacePartition/Octree.cpp \
    ./GraphicsLibrary/Sampling/Sampler.cpp \
    ./GraphicsLibrary/Voxel/Voxeler.cpp \
    ./GraphicsLibrary/Skeleton/ClosedPolygon.cpp \
    ./GraphicsLibrary/Skeleton/GeneralizedCylinder.cpp \
    ./GraphicsLibrary/Skeleton/PriorityQueue.cpp \
    ./GraphicsLibrary/Skeleton/Skeleton.cpp \
    ./GraphicsLibrary/Skeleton/SkeletonExtract.cpp \
    ./Utility/ColorMap.cpp \
    ./Utility/SimpleDraw.cpp \
    ./Utility/Stats.cpp \
    ./GL/VBO/VBO.cpp \
    ./GL/GLee.c \
    ./MathLibrary/Bounding/BoundingBox.cpp \
    ./MathLibrary/Bounding/ConvexHull2.cpp \
    ./MathLibrary/Bounding/ConvexHull3.cpp \
    ./MathLibrary/Bounding/MinOBB2.cpp \
    ./MathLibrary/Bounding/MinOBB3.cpp \
    ./MathLibrary/Deformer/DeformerPanel.cpp \
    ./MathLibrary/Deformer/QVoxelDeformerPanel.cpp \
    ./MathLibrary/Deformer/VoxelDeformer.cpp \
    ./MathLibrary/Deformer/FFD.cpp \
    ./MathLibrary/Deformer/QFFD.cpp \
    ./MathLibrary/Coordiantes/GCDeformation.cpp \
    ./Stacker/EditSuggestion.cpp \
    ./Stacker/HiddenViewer.cpp \
    ./Stacker/Offset.cpp \
    ./Stacker/ShapeState.cpp \
    ./Stacker/StackerPanel.cpp \
    ./Stacker/StackerPreview.cpp \
    ./Stacker/ControllerPanel.cpp \
    ./Stacker/GroupPanel.cpp \
    ./Stacker/QDeformController.cpp \
    ./Stacker/ConcentricGroup.cpp \
    ./Stacker/CoplanarGroup.cpp \
    ./Stacker/Group.cpp \
    ./Stacker/JointGroup.cpp \
    ./Stacker/SymmetryGroup.cpp \
    ./Stacker/Controller.cpp \
    ./Stacker/Cuboid.cpp \
    ./Stacker/GCylinder.cpp \
    ./Stacker/Primitive.cpp
FORMS += ./GUI/Workspace.ui \
    ./GUI/Tools/RotationWidget.ui \
    ./GUI/Tools/MeshInfo.ui \
    ./MathLibrary/Deformer/DeformerWidget.ui \
    ./MathLibrary/Deformer/QVoxelDeformerWidget.ui \
    ./Stacker/ControllerWidget.ui \
    ./Stacker/GroupWidget.ui \
    ./Stacker/StackerWidget.ui
RESOURCES += Workspace.qrc
