# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Workspace
DESTDIR = ./
QT += core gui xml opengl
CONFIG += debug console
DEFINES += QT_LARGEFILE_SUPPORT QT_XML_LIB QT_OPENGL_LIB qh_QHpointer QT_DLL
INCLUDEPATH += ./GeneratedFiles \
    ./GeneratedFiles/Debug \
    . \
    ./GraphicsLibrary/Mesh/SurfaceMesh \
    ./Utility \
    ./Stacker \
    ./GraphicsLibrary/Skeleton \
    ./GraphicsLibrary/Skeleton/Solver/UmfPack_include/UMFPACK \
    ./GraphicsLibrary/Skeleton/Solver/UmfPack_include/AMD \
    ./GraphicsLibrary/Skeleton/Solver/UmfPack_include/UFconfig \
    $(NOINHERIT)
LIBS += -L"./GUI/Viewer/libQGLViewer/QGLViewer/lib" \
    -L"./GraphicsLibrary/Skeleton/Solver/lib" \
    -lopengl32 \
    -lglu32 \
    -lQGLViewerd2 \
    -llibamd \
    -llibumfpack
PRECOMPILED_HEADER = StdAfx.h
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(Workspace.pri)
